# Generated by Django 3.1.6 on 2021-03-14 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.AddField(
            model_name='subject',
            name='period',
            field=models.IntegerField(default=20),
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classScore', models.IntegerField()),
                ('examscore', models.IntegerField()),
                ('totalscore', models.IntegerField()),
                ('position', models.CharField(max_length=5, null=True)),
                ('classterm', models.CharField(max_length=20, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sisapp.subject')),
            ],
        ),
    ]
