# Generated by Django 3.1.6 on 2021-03-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisapp', '0002_auto_20210314_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
