# Generated by Django 3.1.6 on 2021-03-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sisapp', '0003_auto_20210314_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='results',
            options={'verbose_name': 'Results'},
        ),
    ]
