# Generated by Django 3.1.6 on 2021-03-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sisapp', '0004_auto_20210314_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='results',
            options={'verbose_name_plural': 'Results'},
        ),
    ]
