# Generated by Django 3.1.6 on 2021-03-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisapp', '0005_auto_20210314_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='classterm',
        ),
        migrations.AddField(
            model_name='results',
            name='level',
            field=models.CharField(choices=[('primary 1', 'primary 1'), ('primary 2', 'primary 2'), ('primary 3', 'primary 3'), ('primary 4', 'primary 4'), ('primary 5', 'primary 5'), ('primary 6', 'primary 6'), ('JHS 1', 'JHS 1'), ('JHS 2', 'JHS 2'), ('JHS 3', 'JHS 3')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='term',
            field=models.IntegerField(default=1),
        ),
    ]
