# Generated by Django 3.1.6 on 2021-03-14 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisapp', '0008_auto_20210314_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sisapp.level'),
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
    ]
