# Generated by Django 3.1.6 on 2021-03-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisapp', '0012_auto_20210314_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='level',
            field=models.CharField(choices=[('Basic 1 Term 1', 'Basic 1 Term 1'), ('Basic 1 Term 2', 'Basic 1 Term 2'), ('Basic 1 Term 3', 'Basic 1 Term 3'), ('Basic 2 Term 1', 'Basic 2 Term 1'), ('Basic 2 Term 2', 'Basic 2 Term 2'), ('Basic 2 Term 3', 'Basic 2 Term 3'), ('Basic 3 Term 1', 'Basic 3 Term 1'), ('Basic 3 Term 2', 'Basic 3 Term 2'), ('Basic 3 Term 3', 'Basic 3 Term 3'), ('Basic 4 Term 1', 'Basic 4 Term 1'), ('Basic 4 Term 2', 'Basic 4 Term 2'), ('Basic 4 Term 3', 'Basic 4 Term 3'), ('Basic 5 Term 1', 'Basic 5 Term 1'), ('Basic 5 Term 2', 'Basic 5 Term 2'), ('Basic 5 Term 3', 'Basic 5 Term 3'), ('Basic 6 Term 1', 'Basic 6 Term 1'), ('Basic 6 Term 2', 'Basic 6 Term 2'), ('Basic 6 Term 3', 'Basic 6 Term 3'), ('Basic 7 Term 7', 'Basic 7 Term 1'), ('Basic 7 Term 7', 'Basic 7 Term 2'), ('Basic 7 Term 7', 'Basic 7 Term 3'), ('Basic 8 Term 8', 'Basic 8 Term 1'), ('Basic 8 Term 8', 'Basic 8 Term 2'), ('Basic 8 Term 8', 'Basic 8 Term 3'), ('Basic 9 Term 9', 'Basic 9 Term 1'), ('Basic 9 Term 9', 'Basic 9 Term 2'), ('Basic 9 Term 9', 'Basic 9 Term 2')], max_length=17, null=True),
        ),
    ]
