# Generated by Django 3.1.6 on 2021-04-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisapp', '0015_auto_20210314_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='othername',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='firstname',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='firstname'),
        ),
        migrations.AlterField(
            model_name='results',
            name='level',
            field=models.CharField(max_length=17),
        ),
    ]
