# Generated by Django 3.1.6 on 2021-04-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisapp', '0016_auto_20210407_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=15, null=True, verbose_name='mobile number'),
        ),
    ]
