# Generated by Django 3.1.6 on 2021-04-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sisapp', '0017_myuser_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='results',
            options={'verbose_name_plural': 'Results'},
        ),
    ]
