# Generated by Django 3.1.6 on 2020-04-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisapp', '0020_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final',
            name='year',
            field=models.CharField(max_length=8),
        ),
    ]
