# Generated by Django 3.1.6 on 2020-04-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisapp', '0021_auto_20200401_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='final',
            name='agg',
        ),
        migrations.RemoveField(
            model_name='final',
            name='avg',
        ),
        migrations.AddField(
            model_name='final',
            name='aggregate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='final',
            name='average',
            field=models.FloatField(default=0.0),
        ),
    ]
