# Generated by Django 3.1.6 on 2021-04-21 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisapp', '0022_auto_20200401_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.IntegerField()),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('flw_ref', models.CharField(max_length=20)),
                ('tx_ref', models.CharField(default='hooli-tx-1920bbtyt', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
